from typing import Literal

from fastapi import FastAPI, Depends, HTTPException, status
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from pydantic import BaseModel, Field
from kubernetes import client, config


QUOTA_PROFILES = {
    "small": {
        "cpu": "2",
        "memory": "4Gi",
        "pods": "10"
    },
    "medium": {
        "cpu": "8",
        "memory": "16Gi",
        "pods": "30"
    },
    "large": {
        "cpu": "16",
        "memory": "32Gi",
        "pods": "60"
    }
}


# ============================================================
# 1. FASTAPI APPLICATION
# ============================================================

app = FastAPI(
    title="Platform API",
    version="0.2.0",
    description="Internal Platform API for governed Kubernetes capabilities"
)


# ============================================================
# 2. KUBERNETES CONNECTION
# ============================================================
#
# The Platform API uses its own Kubernetes identity.
#
# platform-api.kubeconfig contains the token associated with:
#
#   ServiceAccount:
#       platform-system / platform-api
#
# Kubernetes RBAC restricts that identity to the operations
# explicitly granted to the Platform API.
#

config.load_kube_config(
    config_file="platform-api.kubeconfig"
)

k8s = client.CoreV1Api()


# ============================================================
# 3. API AUTHENTICATION
# ============================================================
#
# Protected endpoints expect:
#
#   Authorization: Bearer <token>
#
# These tokens are intentionally simple for the laboratory.
# In production this layer would normally be replaced by
# OIDC / OAuth2 and a corporate Identity Provider.
#

security = HTTPBearer()


# ============================================================
# 4. LAB USERS / TOKENS
# ============================================================
#
# Northbound authentication:
#
#   Consumer -> Platform API
#
# These are NOT Kubernetes tokens.
# They only authenticate consumers against our Platform API.
#

TOKENS = {
    "viewer-token": {
        "username": "viewer-user",
        "role": "viewer"
    },

    "developer-token": {
        "username": "developer-user",
        "role": "developer"
    }
}


# ============================================================
# 5. PLATFORM REQUEST MODEL
# ============================================================
#
# IMPORTANT:
#
# The consumer no longer chooses the Kubernetes namespace name.
#
# Instead, the consumer expresses intent:
#
#   application
#   team
#   environment
#   size
#
# The Platform API derives the Kubernetes implementation.
#
# Literal automatically restricts environment and size to the
# supported Golden Path values.
#

class NamespaceRequest(BaseModel):

    application: str = Field(
        min_length=3,
        max_length=30,
        description="Application name"
    )

    team: str = Field(
        min_length=3,
        max_length=30,
        description="Owning team"
    )

    environment: Literal[
        "dev",
        "test",
        "prod"
    ]

    size: Literal[
        "small",
        "medium",
        "large"
    ]


# ============================================================
# 6. AUTHENTICATION
# ============================================================
#
# Authentication answers:
#
#   "Who are you?"
#
# The Bearer Token identifies the Platform API consumer.
#

def get_current_user(
    credentials: HTTPAuthorizationCredentials = Depends(security)
):

    token = credentials.credentials

    user = TOKENS.get(token)

    if not user:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid authentication token"
        )

    return user


# ============================================================
# 7. AUTHORIZATION
# ============================================================
#
# Authorization answers:
#
#   "What are you allowed to do?"
#
# viewer:
#   GET namespaces
#
# developer:
#   GET namespaces
#   POST namespaces
#

def require_developer(
    user=Depends(get_current_user)
):

    if user["role"] != "developer":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Insufficient permissions"
        )

    return user


# ============================================================
# 8. PLATFORM NAMING POLICY
# ============================================================
#
# Namespace names are generated by the platform.
#
# The consumer requests:
#
#   application = payments
#   environment = dev
#
# The platform generates:
#
#   payments-dev
#
# This prevents consumers from defining arbitrary Kubernetes
# namespace names and establishes a predictable convention.
#

def build_namespace_name(
    request: NamespaceRequest
) -> str:

    return f"{request.application}-{request.environment}".lower()


# ============================================================
# 9. HEALTH ENDPOINT
# ============================================================
#
# Public endpoint.
#
# This endpoint intentionally does not require authentication.
# It can later be used by:
#
#   - monitoring
#   - Kubernetes probes
#   - load balancers
#

@app.get("/health")
def health():

    return {
        "status": "ok"
    }


# ============================================================
# 10. LIST NAMESPACES
# ============================================================
#
# Any authenticated Platform API consumer can list namespaces.
#
# The Kubernetes operation itself is executed using the
# ServiceAccount configured in platform-api.kubeconfig.
#

@app.get("/api/v1/namespaces")
def list_namespaces(
    user=Depends(get_current_user)
):

    namespaces = k8s.list_namespace()

    return {
        "requested_by": user["username"],
        "items": [
            {
                "name": ns.metadata.name,
                "status": ns.status.phase
            }
            for ns in namespaces.items
        ]
    }


# ============================================================
# 11. CREATE NAMESPACE
# ============================================================
#
# Only consumers with the developer role can use this endpoint.
#
# Notice the separation of responsibilities:
#
# Consumer:
#   expresses intent
#
# Platform API:
#   validates request
#   applies naming policy
#   generates Kubernetes metadata
#
# Kubernetes:
#   enforces RBAC and creates the resource
#

@app.post(
    "/api/v1/namespaces",
    status_code=status.HTTP_201_CREATED
)
def create_namespace(
    request: NamespaceRequest,
    user=Depends(require_developer)
):

    # --------------------------------------------------------
    # 1. Platform naming policy
    # --------------------------------------------------------

    namespace_name = build_namespace_name(request)

    # --------------------------------------------------------
    # 2. Capacity profile selected by the consumer
    # --------------------------------------------------------

    quota_profile = QUOTA_PROFILES[request.size]

    # --------------------------------------------------------
    # 3. Kubernetes Namespace object
    # --------------------------------------------------------

    namespace = client.V1Namespace(
        metadata=client.V1ObjectMeta(
            name=namespace_name,
            labels={
                "platform.company/application": request.application,
                "platform.company/team": request.team,
                "platform.company/environment": request.environment,
                "platform.company/size": request.size,
                "platform.company/managed-by": "platform-api"
            }
        )
    )

    try:

        # ----------------------------------------------------
        # 4. Create Namespace
        # ----------------------------------------------------

        k8s.create_namespace(namespace)

        # ----------------------------------------------------
        # 5. Create ResourceQuota
        #
        # The user only selected:
        #
        #   size = small | medium | large
        #
        # The Platform API translates that into concrete
        # Kubernetes resource limits.
        # ----------------------------------------------------

        quota = client.V1ResourceQuota(
            metadata=client.V1ObjectMeta(
                name="platform-quota",
                namespace=namespace_name,
                labels={
                    "platform.company/managed-by": "platform-api",
                    "platform.company/profile": request.size
                }
            ),
            spec=client.V1ResourceQuotaSpec(
                hard={
                    "requests.cpu": quota_profile["cpu"],
                    "requests.memory": quota_profile["memory"],
                    "pods": quota_profile["pods"]
                }
            )
        )

        k8s.create_namespaced_resource_quota(
            namespace=namespace_name,
            body=quota
        )

        # ----------------------------------------------------
        # 6. API response
        # ----------------------------------------------------

        return {
            "status": "created",
            "namespace": namespace_name,
            "application": request.application,
            "team": request.team,
            "environment": request.environment,
            "size": request.size,
            "quota": {
                "cpu": quota_profile["cpu"],
                "memory": quota_profile["memory"],
                "pods": quota_profile["pods"]
            },
            "requested_by": user["username"]
        }

    except client.exceptions.ApiException as e:

        if e.status == 409:

            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail=f"Namespace or quota for '{namespace_name}' already exists"
            )

        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Kubernetes API error: {e.reason}"
        )